'use client';

import { useState, type ChangeEvent, type FormEvent } from 'react';
import Link from 'next/link';
import type { ScenarioGenerationDto } from '@/application/dto/scenario-generation';
import type { MissionDashboardDto } from '@/application/dto/mission-dashboard';
import { apiClient } from '@/client/api-client';
import { Icon } from '@/components/common/icon';
import { StatusPill } from '@/components/common/status-pill';
import { ScenarioMiniMap } from '@/components/scenario/scenario-mini-map';
import { ValidationList } from '@/components/scenario/validation-list';
import { demoScenarioPrompts } from '@/fixtures/scenario-prompts';
import { useI18n } from '@/i18n/i18n-provider';

export function ScenarioArchitect({ initialScenarios }: { initialScenarios: readonly Record<string, unknown>[] }) {
  const { t } = useI18n();
  const [prompt, setPrompt] = useState<string>(demoScenarioPrompts[0] ?? '');
  const [difficulty, setDifficulty] = useState<'easy' | 'normal' | 'hard' | 'crisis'>('hard');
  const [durationDays, setDurationDays] = useState(7);
  const [seed, setSeed] = useState(384719);
  const [result, setResult] = useState<ScenarioGenerationDto | null>(null);
  const [scenarios, setScenarios] = useState(initialScenarios);
  const [busy, setBusy] = useState(false);
  const [activation, setActivation] = useState<MissionDashboardDto | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(null); setActivation(null);
    try {
      const generated = await apiClient.generateScenario({ prompt, difficulty, durationDays, seed });
      setResult(generated);
      setScenarios(await apiClient.scenarios());
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); }
    finally { setBusy(false); }
  }
  async function activate(id: string) {
    setBusy(true); setError(null);
    try { setActivation(await apiClient.activateScenario(id)); }
    catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); }
    finally { setBusy(false); }
  }

  return <div className="scenario-layout">
    <form className="scenario-form panel" onSubmit={generate}>
      <div className="section-label"><span><Icon name="spark" size={14}/>{t('Scenario brief')}</span><StatusPill tone="violet">{t('AI structured output')}</StatusPill></div>
      <label>{t('Mission prompt')}<textarea value={prompt} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setPrompt(event.target.value)} rows={7}/></label>
      <div className="preset-row">{demoScenarioPrompts.map((value, index) => <button type="button" key={value} onClick={() => setPrompt(value)}>{t('Preset')} {index + 1}</button>)}</div>
      <div className="form-grid"><label>{t('Difficulty')}<select value={difficulty} onChange={(event: ChangeEvent<HTMLSelectElement>) => setDifficulty(event.target.value as typeof difficulty)}><option value="easy">{t('easy')}</option><option value="normal">{t('normal')}</option><option value="hard">{t('hard')}</option><option value="crisis">{t('crisis')}</option></select></label><label>{t('Duration')}<input type="number" min="1" max="30" value={durationDays} onChange={(event: ChangeEvent<HTMLInputElement>) => setDurationDays(Number(event.target.value))}/><small>{t('days')}</small></label><label>{t('Seed')}<input type="number" value={seed} onChange={(event: ChangeEvent<HTMLInputElement>) => setSeed(Number(event.target.value))}/></label></div>
      <button className="primary-action" type="submit" disabled={busy || prompt.length < 10}><Icon name="spark" size={17}/>{t(busy ? 'Generating and validating…' : 'Generate scenario')}</button>
      <div className="process-chain"><span>DeepSeek</span><i>→</i><span>JSON Schema</span><i>→</i><span>{t('Domain validation')}</span><i>→</i><span>{t('Balance simulation')}</span><i>→</i><span>{t('Luna fallback')}</span></div>
      {error ? <div className="inline-error"><Icon name="alert" size={15}/>{error}</div> : null}
    </form>

    <section className="scenario-result panel">
      {!result ? <div className="large-empty"><Icon name="moon" size={42}/><h2>{t('No generated world yet')}</h2><p>{t('The built-in scenario remains available. Generate a new structured world to inspect its map and validation evidence.')}</p></div> : <>
        <header className="scenario-result__head"><div><span className="eyebrow">{t('Generated by')} {result.source}</span><h2>{result.scenario.name}</h2><p>{result.scenario.description}</p></div><div><StatusPill tone={result.validation.valid ? 'mint' : 'red'}>{t(result.validation.valid ? 'validated' : 'rejected')}</StatusPill>{result.fallbackUsed ? <StatusPill tone="violet">{t('Luna fallback')}</StatusPill> : null}</div></header>
        <div className="scenario-preview-grid"><ScenarioMiniMap world={result.scenario.world}/><div className="scenario-facts"><span><small>{t('Sites')}</small><strong>{result.scenario.world.nodes.length}</strong></span><span><small>{t('Rovers')}</small><strong>{result.scenario.roverTemplates.length}</strong></span><span><small>{t('Orders count')}</small><strong>{result.scenario.orderTemplates.length}</strong></span><span><small>{t('Impossible')}</small><strong>{result.validation.impossibleOrderCodes.length}</strong></span><span><small>{t('Balance')}</small><strong>{Math.round(result.balance.successRate * 100)}%</strong></span><span><small>{t('Seed')}</small><strong>{result.scenario.seed}</strong></span></div></div>
        <ValidationList report={result.validation}/>
        <button className="secondary-action" type="button" onClick={() => void activate(result.scenario.id)} disabled={busy || !result.validation.valid}>{t('Activate this mission')} <Icon name="arrow" size={14}/></button>
      </>}
    </section>

    <section className="saved-scenarios panel"><div className="section-label"><span>{t('Saved scenarios')}</span><small>{scenarios.length} {t('versions available')}</small></div><div className="saved-scenario-list">{scenarios.map((scenario, index) => <article key={String(scenario.id ?? index)}><div><strong>{String(scenario.name ?? scenario.id)}</strong><small>{t(String(scenario.difficulty ?? ''))} · {String(scenario.source ?? '')}</small></div><button type="button" onClick={() => void activate(String(scenario.id))} disabled={busy}>{t('Activate')}</button></article>)}</div>{activation ? <div className="activation-success"><Icon name="check" size={16}/>{t('Mission activated')}: {activation.scenario.name}. <Link href="/">{t('Open Mission Control')}</Link></div> : null}</section>
  </div>;
}
